ltslam:

  sessions_dir: "/home/user/Desktop/ltslam-tuto/data_parsed/" # end with / 

  central_sess_name: "01" # should be same as the directory name of that session
  query_sess_name: "02" # should be same as the directory name of that session
  
  save_directory: "/home/user/Desktop/ltslam-tuto/data_ltslam/0102/" # end with "/"

  is_display_debug_msgs: false

  loopFitnessScoreThreshold: 0.7

  kNumSCLoopsUpperBound: 200 # if you use an enough number, use all the detected loops 
  kNumRSLoopsUpperBound: 200 # if you use an enough number, use all the detected loops 

  numberOfCores: 16 # currently hard-coded in the utility.cpp

